### ISSUE TITLE
[Corrigir transcrição automática] Como Batizar os Elementos de uma Aplicação

### ISSUE THREAD

**Issue by luccosta** [luccosta/ros-brasil-traducao#1]
Dividir os Pull Requests em:

- [x]  1 -> 156 (#5)
- [x]  157 -> 312 (#12)
- [x] 313 -> 468 (#11)
- [x] 469 -> 624 (#8)
- [x] 625 -> 781 (#6)

**Comment by luccosta** [comment]
Vou pegar de 1 -> 156.

**Comment by chapulina** [comment]
Vou pegar 625 -> 781

**Comment by chapulina** [comment]
Vou pegar 469 -> 624

**Comment by chapulina** [comment]
Vou pegar 313 -> 468

**Comment by luccosta** [comment]
O arquivo foi movido para <i>corrigido</i> o que encerra o Issue.
